### ISSUE TITLE
No option for radius of button

### ISSUE THREAD

**Issue by KartikayKK** [Omega-R/OmegaCenterIconButton#12]

**Comment by RomanTcv** [comment]
Hi @KartikayKK.
Maybe you are talking about MaterialButton ? 

```
    <com.google.android.material.button.MaterialButton
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:icon="@drawable/ic_triangles"
            android:text="@string/button_enter_and_get_loan"
            app:cornerRadius="16dp"
            app:iconGravity="textStart"
            app:iconTint="@color/white"
            app:iconSize="24dp" />
```
MaterialButton supports iconGravity="textStart" (equal center) by default.

**Comment by KartikayKK** [comment]
Thanks for the help,but I wanted to know if i could provide a radius to OmegaCenterIconButton.

**Comment by RomanTcv** [comment]
@KartikayKK 
Unfortunately you can't. 
You have to choices: 
- use MaterialButton
- apply custom background drawable (rounded) for OmegaCenterIconButton.

**Comment by KartikayKK** [comment]
Yes I applied the background,thanks for the help. And awesome library really easy to implement.
