### ISSUE TITLE
Attributes can't be set via styles

### ISSUE THREAD

**Issue by jolaf** [Omega-R/OmegaCenterIconButton#16]
Attributes `layout_width`, `layout_height` and `drawableTint` (and maybe some others) work correctly if specified in `<com.omega_r.libs.OmegaCenterIconButton>` tag in XML layout, but are ignored if specified via `<style>` tag in `styles.xml` and then added to `<com.omega_r.libs.OmegaCenterIconButton>` tag via its `style` attribute or using a theme.

**Comment by anton-knyazev** [comment]
Hello. Thanks for your report. Try version 
	       ` implementation 'com.github.Omega-R:OmegaCenterIconButton:5473755eb6'`

**Comment by jolaf** [comment]
I tried that and it worked. Then I found out that older version in fact works too, so I probably did something wrong or looked the wrong way the first time. I'm so sorry to bother you and to take your time for nothing. :(

Very useful library, by the way, helps much! Thank you very much for it!
